# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\desktop2\projects\pyqt5\mcstatus\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 546)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.909, y2:0.852955, stop:0 rgba(214, 214, 214, 255), stop:1 rgba(235, 235, 235, 255));\n"
"}\n"
"\n"
"\n"
"QGroupBox {\n"
"padding-top: 15px;\n"
"}\n"
"\n"
"QFrame, QGroupBox, QDoubleSpinBox {\n"
"border-radius: 3px;\n"
"font-size: 20px;\n"
"    color: rgb(35, 35, 35);\n"
"}\n"
"\n"
"QLabel {\n"
"border: None;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title = QtWidgets.QLabel(self.frame)
        self.title.setObjectName("title")
        self.horizontalLayout_3.addWidget(self.title)
        self.verticalLayout.addWidget(self.frame)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.edit_server_address = QtWidgets.QLineEdit(self.frame_5)
        self.edit_server_address.setObjectName("edit_server_address")
        self.horizontalLayout_6.addWidget(self.edit_server_address)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.edit_discord_webhook = QtWidgets.QLineEdit(self.frame_2)
        self.edit_discord_webhook.setObjectName("edit_discord_webhook")
        self.horizontalLayout.addWidget(self.edit_discord_webhook)
        self.check_send_logs = QtWidgets.QCheckBox(self.frame_2)
        self.check_send_logs.setChecked(True)
        self.check_send_logs.setObjectName("check_send_logs")
        self.horizontalLayout.addWidget(self.check_send_logs)
        self.verticalLayout.addWidget(self.frame_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.line_overworld_x = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.line_overworld_x.setMinimum(-999999.0)
        self.line_overworld_x.setMaximum(999999.0)
        self.line_overworld_x.setObjectName("line_overworld_x")
        self.horizontalLayout_5.addWidget(self.line_overworld_x)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.line_overworld_z = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.line_overworld_z.setMinimum(-999999.0)
        self.line_overworld_z.setMaximum(999999.0)
        self.line_overworld_z.setObjectName("line_overworld_z")
        self.horizontalLayout_5.addWidget(self.line_overworld_z)
        self.horizontalLayout_5.setStretch(1, 50)
        self.horizontalLayout_5.setStretch(3, 50)
        self.horizontalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.line_nether_x = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.line_nether_x.setMinimum(-999999.0)
        self.line_nether_x.setMaximum(999999.0)
        self.line_nether_x.setObjectName("line_nether_x")
        self.horizontalLayout_4.addWidget(self.line_nether_x)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.line_nether_z = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.line_nether_z.setMinimum(-999999.0)
        self.line_nether_z.setMaximum(999999.0)
        self.line_nether_z.setObjectName("line_nether_z")
        self.horizontalLayout_4.addWidget(self.line_nether_z)
        self.horizontalLayout_4.setStretch(1, 50)
        self.horizontalLayout_4.setStretch(3, 50)
        self.horizontalLayout_7.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_timestamp = QtWidgets.QLabel(self.frame_3)
        self.label_timestamp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_timestamp.setObjectName("label_timestamp")
        self.horizontalLayout_2.addWidget(self.label_timestamp)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.log = QtWidgets.QListWidget(self.frame_4)
        self.log.setObjectName("log")
        self.verticalLayout_2.addWidget(self.log)
        self.verticalLayout.addWidget(self.frame_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Minecraft Utility"))
        self.label_9.setText(_translate("MainWindow", "Server Address:"))
        self.label.setText(_translate("MainWindow", "Discord Webhook:"))
        self.check_send_logs.setText(_translate("MainWindow", "Send Logs"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Portal Calculator"))
        self.groupBox.setTitle(_translate("MainWindow", "Overworld"))
        self.label_4.setText(_translate("MainWindow", "X"))
        self.label_5.setText(_translate("MainWindow", "Z"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Nether"))
        self.label_6.setText(_translate("MainWindow", "X"))
        self.label_7.setText(_translate("MainWindow", "Z"))
        self.label_8.setText(_translate("MainWindow", "Log"))
        self.label_timestamp.setText(_translate("MainWindow", "00:00:00pm"))
import resources_rc
